# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup git config
        run: |
          git config user.name "Sadanand Pai"
          git config user.email "sadypai@gmail.com"
          
      - name: setup deployment
        run: |
          npm install
          rm -rf dist
          npm run build
          git add dist -f
          git commit -m "build files from github action"
          git push
